server:
  port: 7529
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 604800
spring:
  profiles:
    active: dev
  application:
    name: FrankApiBackend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/********
    username: root
    password: ********
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  session:
    timeout: 86400
    store-type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    # password: ********
    timeout: 86400
  #  邮箱配置 todo 修改为自己的邮箱发送配置 password为邮箱授权码
  mail:
    host: smtp.qq.com
    username: ********
    password: ********
    emailFrom: ********
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 是否将数据库中的下划线命名字段自动映射到 Java 对象的驼峰命名字段
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名，since 3.3.0
      logic-delete-value: 1         # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0     # 逻辑未删除值（默认为 0）
# FrankAPI-SDK 配置
qi:
  api:
    client:
      # 本地测试网关地址
      host: ********
cos:
  client:
    accessKey: ********
    secretKey: ********
    region: ********
    bucket: ********
    cos-host: ********
# 微信支付配置
wx:
  pay:
    appId: ********
    mchId: ********
    apiV3Key: ********
    sandbox: false # 是否沙箱环境
    privateKeyPath: classpath:/pem/apiclient_key.pem
    privateCertPath: classpath:/pem/apiclient_cert.pem
    # 本地测试用 ngrok 内网穿透
    notifyUrl: https://beloved-massive-sheepdog.ngrok-free.app/api/order/notify/order
# 支付宝支付配置
alipay:
  appId: ********
  sellerId: ********
  # 是否沙箱环境
  sandbox: false
  # 本地测试用 ngrok 内网穿透
  notifyUrl: https://beloved-massive-sheepdog.ngrok-free.app/api/order/notify/order
  returnUrl: ********
  private-key: ********
  ali-pay-public-key: ********
dubbo:
  application:
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848